/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eieruhr.view;

/**
 *
 * @author Christian
 */
public class Ansicht extends javax.swing.JPanel
{

  /**
   * @return the zaehler
   */
  public javax.swing.JLabel getZaehler()
  {
    return zaehler;
  }

  /**
   * @param zaehler the zaehler to set
   */
  public void setZaehler(javax.swing.JLabel zaehler)
  {
    this.zaehler = zaehler;
  }

  /**
   * Creates new form Ansicht2
   */
  public Ansicht()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    zaehler = new javax.swing.JLabel();

    setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

    zaehler.setText("0");
    add(zaehler);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel zaehler;
  // End of variables declaration//GEN-END:variables
}
