/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eieruhr.view;

/**
 *
 * @author Christian
 */
public class View extends javax.swing.JFrame
{

  /**
   * @return the btnStart
   */
  public javax.swing.JButton getBtnStart()
  {
    return btnStart;
  }

  /**
   * @return the btnStop
   */
  public javax.swing.JButton getBtnStop()
  {
    return btnStop;
  }

  /**
   * Creates new form View
   */
  public View()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jPanel1 = new javax.swing.JPanel();
    btnStart = new javax.swing.JButton();
    btnStop = new javax.swing.JButton();
    eieruhr1 = new eieruhr.Eieruhr();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Eieruhr");

    btnStart.setText("Start");
    btnStart.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseReleased(java.awt.event.MouseEvent evt)
      {
        btnStartMouseReleased(evt);
      }
    });
    jPanel1.add(btnStart);

    btnStop.setText("Stop");
    btnStop.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseReleased(java.awt.event.MouseEvent evt)
      {
        btnStopMouseReleased(evt);
      }
    });
    jPanel1.add(btnStop);

    getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

    eieruhr1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
    getContentPane().add(eieruhr1, java.awt.BorderLayout.CENTER);

    setSize(new java.awt.Dimension(416, 339));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnStartMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnStartMouseReleased
  {//GEN-HEADEREND:event_btnStartMouseReleased
    eieruhr1.start();
  }//GEN-LAST:event_btnStartMouseReleased

  private void btnStopMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnStopMouseReleased
  {//GEN-HEADEREND:event_btnStopMouseReleased
    eieruhr1.stop();
  }//GEN-LAST:event_btnStopMouseReleased

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new View().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnStart;
  private javax.swing.JButton btnStop;
  private eieruhr.Eieruhr eieruhr1;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
